### ISSUE TITLE
async_discovery_use_separate_thread_per_request is missing from discovery protocol section

### ISSUE THREAD

**Issue by vdzhuvinov** [belaban/jgroups.org#1]
I just noticed that the **async_discovery_use_separate_thread_per_request** parameter is not documented on the website at http://www.jgroups.org/manual/html/protlist.html#Discovery

**Comment by belaban** [comment]
You're looking at the old manual; select [1] from jgroups.org / Manual

[1] http://www.jgroups.org/manual4/index.html#Discovery
